name: wildlife_camera_mobile
description: Mobile app for ESP32 Wildlife Camera monitoring and control
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  
  # State Management
  provider: ^6.0.5
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  
  # Networking and WebSocket
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Notifications
  flutter_local_notifications: ^15.1.1
  firebase_messaging: ^14.6.9
  awesome_notifications: ^0.8.2
  
  # Camera and Media
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Utility
  intl: ^0.18.1
  uuid: ^4.1.0
  logger: ^2.0.2+1
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  
  # Charts and Visualization
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^23.1.39
  
  # QR Code and Scanning
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2
  
  # File Handling
  file_picker: ^6.0.0
  open_file: ^3.3.2
  share_plus: ^7.2.1
  
  # Background Tasks
  workmanager: ^0.5.1
  
  # Security
  flutter_secure_storage: ^9.0.0
  
  # AR and 3D Visualization
  arcore_flutter_plugin: ^0.1.0
  ar_flutter_plugin: ^0.7.3
  vector_math: ^2.1.4
  flutter_cube: ^0.1.1
  model_viewer_plus: ^1.7.0
  
  # GPS and Location
  geolocator: ^10.1.0
  location: ^5.0.3
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  flutter_compass: ^0.8.0
  
  # ML and AI
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.3.1
  
  # Audio and Speech
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5
  just_audio: ^0.9.36
  audio_waveforms: ^1.0.5
  
  # Gesture and Interaction
  flutter_gesture_recognizer: ^0.2.0
  sensors_plus: ^3.1.0
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting and Analysis
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  
  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/config/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Wildlife
      fonts:
        - asset: assets/fonts/wildlife-icons.ttf

# Platform-specific configuration
flutter_native_splash:
  color: "#2c3e50"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#2c3e50"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Firebase configuration
firebase_options:
  - platform: android
    config: android/app/google-services.json
  - platform: ios
    config: ios/Runner/GoogleService-Info.plist