apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wildcam-aws-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: wildcam-multicloud
  
  source:
    repoURL: https://github.com/thewriterben/WildCAM_ESP32.git
    targetRevision: main
    path: helm/wildcam
    helm:
      releaseName: wildcam-aws
      values: |
        global:
          environment: production
          cloudProvider: aws
        
        backend:
          replicaCount: 5
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 8Gi
        
        multiCloud:
          aws:
            region: us-west-2
            s3:
              bucket: wildcam-wildlife-data-aws
        
        ingress:
          hosts:
            - host: aws.wildcam.example.com
              paths:
                - path: /
                  pathType: Prefix
  
  destination:
    server: https://wildcam-aws-eks.us-west-2.eks.amazonaws.com
    namespace: wildcam-production
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
