apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- postgres.yaml
- redis.yaml
- backend.yaml
- frontend.yaml
- nginx.yaml
- monitoring.yaml

commonLabels:
  app.kubernetes.io/name: wildcam
  app.kubernetes.io/part-of: esp32-wildlife-monitoring

namespace: wildcam