apiVersion: v1
kind: Secret
metadata:
  name: wildcam-secrets
  namespace: wildcam
type: Opaque
stringData:
  postgres-password: "CHANGE_ME_IN_PRODUCTION"
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  secret-key: "CHANGE_ME_IN_PRODUCTION"
  influxdb-token: "CHANGE_ME_IN_PRODUCTION"
  aws-access-key: ""
  aws-secret-key: ""